// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: process_rule_type.proto

package iochti.processRuleType.grpc;

public interface ProcessRuleTypeByIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.ProcessRuleTypeByIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string processGroupTypeId = 1;</code>
   */
  java.lang.String getProcessGroupTypeId();
  /**
   * <code>optional string processGroupTypeId = 1;</code>
   */
  com.google.protobuf.ByteString
      getProcessGroupTypeIdBytes();
}
