// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: process_rule_type.proto

package iochti.processRuleType.grpc;

public final class ProcessRuleTypeProto {
  private ProcessRuleTypeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ProcessRuleType_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_ProcessRuleType_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ProcessRuleTypeByIdRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_ProcessRuleTypeByIdRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027process_rule_type.proto\022\005proto\032\033google" +
      "/protobuf/empty.proto\"?\n\017ProcessRuleType" +
      "\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\022\n\nparameters" +
      "\030\003 \001(\t\"8\n\032ProcessRuleTypeByIdRequest\022\032\n\022" +
      "processGroupTypeId\030\001 \001(\t2\327\002\n\026ProcessRule" +
      "TypeService\022Q\n\022GetProcessRuleType\022!.prot" +
      "o.ProcessRuleTypeByIdRequest\032\026.proto.Pro" +
      "cessRuleType\"\000\022I\n\025CreateProcessRuleType\022" +
      "\026.proto.ProcessRuleType\032\026.proto.ProcessR" +
      "uleType\"\000\022I\n\025UpdateProcessRuleType\022\026.pro",
      "to.ProcessRuleType\032\026.proto.ProcessRuleTy" +
      "pe\"\000\022T\n\025DeleteProcessRuleType\022!.proto.Pr" +
      "ocessRuleTypeByIdRequest\032\026.google.protob" +
      "uf.Empty\"\000B0\n\026iochti.processRuleTypeB\024Pr" +
      "ocessRuleTypeProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_proto_ProcessRuleType_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ProcessRuleType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_ProcessRuleType_descriptor,
        new java.lang.String[] { "Id", "Name", "Parameters", });
    internal_static_proto_ProcessRuleTypeByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_ProcessRuleTypeByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_ProcessRuleTypeByIdRequest_descriptor,
        new java.lang.String[] { "ProcessGroupTypeId", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
