// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: process_rule_type.proto

package iochti.processRuleType.grpc;

public interface ProcessRuleTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.ProcessRuleType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>optional string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>optional string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string parameters = 3;</code>
   */
  java.lang.String getParameters();
  /**
   * <code>optional string parameters = 3;</code>
   */
  com.google.protobuf.ByteString
      getParametersBytes();
}
